SaintsRobotics/RapidReact2022

- PLAN.md
- TESTING.md
- src/main/java/frc/robot/Utils.java
- src/test/java/UtilityTest.java
this should have been done in #11
> style: formatted tests

- .vscode/settings.json
- src/main/java/frc/robot/subsystems/SwerveDriveSubsystem.java
> feat: heading correction

- src/main/java/frc/robot/Limelight.java
- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/commands/LimelightAimingCommand.java
> feat: vision

- README.md
PRs that add new features should update this README
> docs: added current status to README

- src/main/java/frc/robot/HardwareMap.java
- src/main/java/frc/robot/subsystems/SwerveModule.java
should work but if you don't trust me you can test it on the bot
> refactor: change how SwerveModule hardware is constructed

- src/main/java/frc/robot/RobotContainer.java
they were unnecessary and wouldn't have worked because they weren't being called periodically.
> chore: removed smart dashboard calls

- AUTONPLAN.md
> docs: Updating Auton strategies

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/ShooterSubsystem.java
Changed shooter rpm, changed minimum and maximum speeds for arm, changed order of autonomous
> chore: updated various speeds

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/commands/AutonShoot.java
- src/main/java/frc/robot/commands/ShooterCommand.java
- src/main/java/frc/robot/subsystems/ShooterSubsystem.java
made code to support the second flywheel
> feat: second flywheel

- src/main/java/frc/robot/Constants.java
> fix: fixed servo constants

- src/main/java/frc/robot/Constants.java
> fixed servo values.

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/commands/AutonShoot.java
- src/main/java/frc/robot/commands/ShooterCommand.java
- src/main/java/frc/robot/subsystems/ShooterSubsystem.java
shooter values have been tuned - code works from about 0.5 meters away
> Second flywheel

- src/main/java/frc/robot/subsystems/SwerveDriveSubsystem.java
This was partially added to #124 but I did it better here.
> refactor: simulate rotation for pathweaver

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/ClimberSubsystem.java
Doesn't change any functionality (apart from renaming a SmartDashboard call). Makes the code a lot cleaner. Has been tested in the simulator.
> refactor: cleaned up ClimberSubsystem

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/subsystems/ShooterSubsystem.java
Fixes bugs that were added in #134, #133, and #130. Also renames and reorders some SmartDashboard calls.
> fix: telemetry and whitespace

- src/main/java/frc/robot/RobotContainer.java
Before the code would have crashed if the path was not set.
> fix: changed default path to BlueHangar

- src/main/java/frc/robot/Utils.java
Also adds an import for SmartDashboard so the link in the javadoc works.
> feat: telemetry is enabled during test mode

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/commands/ShootCommand.java
- src/main/java/frc/robot/commands/ShooterCommand.java
- src/main/java/frc/robot/subsystems/ShooterSubsystem.java
code for the new 52:18 gear ratio for the top flywheel and the change in shooter angle
> fix: shooter

- README.md
> docs: removed unnecessary and unfollowed line in readme

- src/main/java/frc/robot/RobotContainer.java
written better
re-implemented the switch and sendable functionality (from threeballauton)
> Auton robot container

- simgui.json
- src/main/java/frc/robot/Utils.java
- src/main/java/frc/robot/subsystems/ClimberSubsystem.java
- src/main/java/frc/robot/subsystems/ShooterSubsystem.java
- src/main/java/frc/robot/subsystems/SwerveDriveSubsystem.java
- src/main/java/frc/robot/subsystems/SwerveModule.java
> perf: reduce telemetry

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
> Good changes from districts
